### ISSUE TITLE
PhysicsSim doesn't work with init_velocities

### ISSUE THREAD

**Issue by Jwata** [udacity/RL-Quadcopter-2#1]
When I was experimenting, I found a bug in `PhysicsSim`.  
It doesn't work with `init_velocities` properly. please check the following sample.  
I will create a pull request for this bug.

```
# init
sim = PhysicsSim(init_velocities=np.array([0.0, 0.0, 0.0]))
sim.v
=> array([0., 0., 0.])
sim.init_velocities
=> array([0., 0., 0.])

# take step
sim.next_timestep([0.0, 0.0, 0.0, 0.0])

sim.init_velocities
=> array([ 0.    ,  0.    , -0.1962]) # init_velocities has been changed

sim.reset()

sim.v
=> array([ 0.    ,  0.    , -0.1962]) # initial v didn't get reset properly due to the updated init_velocities

**Comment by justinsolms** [comment]
I have fixed the instability problem. It was related to the drag not properly computed. I would like to know if I can push the result. Kind regards - Justin

**Comment by abhiojha8** [comment]
We have fixed the formula for this. Thanks :)
