### ISSUE TITLE
visualization/rendering the training like in openai gym

### ISSUE THREAD

**Issue by nyck33** [udacity/RL-Quadcopter-2#10]
I posted a question on Datascience Stackexchange:  https://datascience.stackexchange.com/questions/47526/what-are-some-ways-to-render-a-ddpg-autonomous-quadcopter-like-openai-gym

What are some ways to do this?

**Comment by abhiojha8** [comment]
"Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks"
