### ISSUE TITLE
Possible unstable velocity damping dynamics

### ISSUE THREAD

**Issue by justinsolms** [udacity/RL-Quadcopter-2#3]
Hi Alexa

I have placed the quadcopter physics into AI Gym. I shall include a GitHub repo link to that in a subsequent post. I have checked the physics lines of your code with mine and there is no difference. That repo link I'll send has the notebook to test the AI gym quadcopter.

I have noticed a velocity divergence for negative x and y  body frame velocities. I'm a bit worried as this may be affecting the RL-Quadcopter project, (although I imagine the RL can compensate if properly trained).

Test:

In level flight at height of 10, zero angles:

I initialize the velocity to vx=10 and that appears to damp away.

![position - vx init to 10](https://user-images.githubusercontent.com/2657045/38453900-7d35e37e-3a5d-11e8-9b9a-f9a9873418cb.png)

![velocity - vx init to 10](https://user-images.githubusercontent.com/2657045/38453902-82d74caa-3a5d-11e8-8274-6ba4a8bfcb61.png)

I initialize the velocity to vx=-10 and that appears to damp away.

![position - vx init to -10](https://user-images.githubusercontent.com/2657045/38453906-93607f06-3a5d-11e8-8d37-f40c6492e3ee.png)

![velocity - vx init to -10](https://user-images.githubusercontent.com/2657045/38453909-986c8ad0-3a5d-11e8-9803-97376cb8dfa1.png)

**Comment by justinsolms** [comment]
My GitHub repo is at https://github.com/justinsolms/gym.git

It is the feature/quadcopter branch.

Kind regards, Justin

**Comment by abhiojha8** [comment]
"Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks"
