### ISSUE TITLE
How is this different from RL-Quadcopter?

### ISSUE THREAD

**Issue by nyck33** [udacity/RL-Quadcopter-2#9]
I was a nanodegree student in Spring 2018 so wondering what changes were made if any.  I know there was some concern about parts of `physics_sim` being incorrect:  https://discussions.udacity.com/t/error-in-physics-sim-py/802561

Please clarify as I am redoing this project's three tasks so I can try to string them together for a take-off -> hover -> land scenario.

**Comment by abhiojha8** [comment]
"Though we are a little late to respond, we suggest you reach out to Udacity support for user-specific issues. 
Thanks"
